CREATE TABLE entry (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    headline VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    asset_id INTEGER NOT NULL,
    FOREIGN KEY (asset_id) REFERENCES asset(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE timeline (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    headline VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    asset_id INTEGER NOT NULL,
    FOREIGN KEY (asset_id) REFERENCES asset(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE asset (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    media VARCHAR(255) NOT NULL,
    credit VARCHAR(255) NOT NULL,
    caption TEXT NOT NULL
);

CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    pwdHash VARCHAR(100) NOT NULL
);
